"""
OpenAPI-generated Xentral tools.

This package turns the official Xentral OpenAPI specification into MCP tools:
- catalog.json  - compiled tool catalog (generated by scripts/generate_catalog.py)
- executor.py   - generic executor that performs any catalog operation
- loader.py     - loads the catalog and builds MCP tool definitions

Note: this package is intentionally a subdirectory so that the tool
auto-discovery in mcp_server.py (which scans xentral/*.py) does not pick
up the executor class as a standalone tool.
"""
