"""
Loader for the OpenAPI tool catalog.

Reads catalog.json (generated by scripts/generate_catalog.py) and builds one
MCP tool per Xentral API operation, each backed by a dynamically created
OpenAPIToolExecutor subclass.
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Set

from mcp_protocol import MCPTool
from xentral.openapi.executor import OpenAPIToolExecutor

logger = logging.getLogger(__name__)

CATALOG_PATH = Path(__file__).parent / "catalog.json"


def _make_executor_class(operation: Dict) -> type:
    """Create a no-arg-constructible executor class bound to one operation."""
    return type(
        f"OpenAPITool_{operation['name']}",
        (OpenAPIToolExecutor,),
        {"_operation": operation, "__doc__": operation["description"]},
    )


def load_openapi_tools(exclude_names: Optional[Set[str]] = None) -> List[MCPTool]:
    """
    Load all catalog operations as MCP tools.

    Args:
        exclude_names: Tool names to skip (e.g. hand-written tools that
            would otherwise collide).

    Returns:
        List of MCPTool instances with full JSON input schemas and an
        attached executor class.
    """
    if not CATALOG_PATH.exists():
        logger.warning(
            "OpenAPI catalog not found at %s - run "
            "'python scripts/generate_catalog.py' to generate it.",
            CATALOG_PATH,
        )
        return []

    with open(CATALOG_PATH, encoding="utf-8") as f:
        catalog = json.load(f)

    exclude_names = exclude_names or set()
    tools: List[MCPTool] = []

    for operation in catalog["tools"]:
        name = operation["name"]
        if name in exclude_names:
            logger.info("Skipping OpenAPI tool %s (overridden by custom tool)", name)
            continue

        tool = MCPTool(
            name=name,
            description=operation["description"],
            parameters=[],
            input_schema=operation["input_schema"],
        )
        tool._implementation_class = _make_executor_class(operation)
        tool._is_implemented = True
        tools.append(tool)

    logger.info(
        "Loaded %d OpenAPI tools from catalog (API %s %s)",
        len(tools),
        catalog.get("api_title"),
        catalog.get("api_version"),
    )
    return tools
